// AUTO-GENERATED by scratchpad/gen-manifest.cjs — the seed list of ready-to-post pieces
// for the /admin Post Queue. Images live in /public/posts. Edit captions in the queue UI
// (overrides persist in the browser); regenerate this file to change the seed.

export interface QueuePost {
  id: string;
  image: string; // "/posts/..png" or "" for a text-only post
  batch: number;
  label: string;
  caption: string;
}

export const POST_MANIFEST: QueuePost[] = [
  {
    "id": "n01",
    "image": "/posts/kindcodex-n01-insight.png",
    "batch": 1,
    "label": "First responder wins",
    "caption": "Here's a pattern that keeps showing up in the response-speed research, and it's a little counter-intuitive: the business that replies first usually wins — and it's often not the strongest option, just the one that was there. The mechanism is simple. A buyer reaches out to a few places, and the first real reply becomes their anchor: it sets the frame of reference everyone else gets quietly compared against. By the time the other options weigh in, the buyer is already half-decided. So \"present beats best\" isn't laziness on the buyer's part — it's just how attention works when someone's ready to move. The useful part: it means speed is a lever almost anyone can pull, regardless of size or budget. Happy to share a quick way to gauge your own average first-response time if that'd be handy — and genuinely curious whether you've watched this play out, on either side of a deal."
  },
  {
    "id": "n02",
    "image": "/posts/kindcodex-n02-illustrated.png",
    "batch": 1,
    "label": "Invisible system illustrated",
    "caption": "\"Instant response\" can sound like magic, or like someone glued to their phone at midnight. It's neither. Here's the plain version of how it actually runs: a lead hits send, a quiet system catches it at any hour, an instant text or email goes back out, and by the time a human looks, a real conversation is already open. The interesting part is that nobody had to be watching for any of that to happen — which is why it keeps working on weekends, mid-job, and at 11pm. Demystified, it's just plumbing that's always on. Curious what the simplest version of that loop might look like for a business like yours? Happy to sketch one out if it'd be useful — or just sit with the diagram."
  },
  {
    "id": "n03",
    "image": "/posts/kindcodex-n03-stat.png",
    "batch": 1,
    "label": "5-minute decay stat hero",
    "caption": "Here's a number that quietly reshaped how we think about timing: in the MIT / InsideSales study of 15,000+ leads, reaching a fresh inquiry within 5 minutes carried roughly 100x the odds of connecting versus waiting 30. The detail most people miss is the shape of the curve - it isn't a gentle slope across the day, it's a cliff inside the first hour. By the time \"I'll get back to them this afternoon\" rolls around, almost all of the math has already played out. So the real lever isn't working harder or faster - it's just being the one who happens to answer in those first few minutes, which turns out to be far more about setup than effort. Curious where your own first-reply window tends to land? It's a surprisingly quick thing to clock - happy to share the simple way we measure it. What's the fastest a brand-new inquiry has ever heard back from you?"
  },
  {
    "id": "n04",
    "image": "/posts/kindcodex-n04-story.png",
    "batch": 1,
    "label": "Two agents, same lead story",
    "caption": "A small scene that stuck with us. Two people got the exact same online inquiry. One thumbed out a reply while standing in the grocery line, and signed about three weeks later. The other planned to handle it properly on Monday, and never heard back. Same lead, same market, two endings. Here is the part that makes the scene make sense: the research on inbound inquiries keeps landing in the same place. The Harvard Business Review study on lead response found that contacting someone within an hour made them far likelier to enter a real conversation than waiting even a few hours, and the curve gets steeper the closer you look at those first five minutes. Curiosity, it turns out, is perishable. A question asked at 9am rarely feels as urgent to the asker by Monday. None of this is a verdict on anyone's calendar, just a pattern worth knowing. If it's ever useful, a quick map of how long that first reply tends to take in a business like yours is the kind of thing we like sharing. Ever had one of these go either way for you?"
  },
  {
    "id": "n05",
    "image": "/posts/kindcodex-n05-comparison.png",
    "batch": 1,
    "label": "47-hour gap comparison",
    "caption": "Here's a pattern that turns up again and again in the lead-response research, laid out as two numbers from the same study. The reply that actually reaches a fresh lead tends to land in minutes. The average B2B inquiry, in Drift's field test of 433 companies, sat for roughly 47 hours before a first reply — and only about 7% got an answer inside five minutes. What's interesting isn't the wait itself; it's how uncontested that first-five-minutes window is. When almost no one is fast, simply being fast becomes a quiet edge. If you're ever curious where your own first-reply time lands on that spectrum, a free response-time check is here whenever it's useful — where would you guess yours falls?"
  },
  {
    "id": "n06",
    "image": "/posts/kindcodex-n06-mockup.png",
    "batch": 1,
    "label": "Missed-call-to-text mockup",
    "caption": "A pattern that's easy to miss if your business runs on the phone: when a call goes to voicemail, most people don't leave a message and don't call back - they just dial the next name on their list (the research lands somewhere around two-thirds to four-fifths, depending on who's counting). An instant text the moment the call drops quietly catches a good share of them before they wander off. Here's the actual message above, free to copy and make your own. Three things are doing the work: it's warm, it names a reason you missed them so it doesn't feel automated, and it ends on a question so there's something easy to reply to. The one piece that's genuinely tricky to pull off by hand is the \"instant, every single time\" part - which is the line between a nice idea and a system that just runs. Curious how you'd word it for your shop - drop a version in the comments and we'll trade notes."
  },
  {
    "id": "n07",
    "image": "/posts/kindcodex-n07-comparison.png",
    "batch": 1,
    "label": "Submit vs Get my quote",
    "caption": "Here is a small pattern we keep noticing in contact forms. The button at the end almost always says \"Submit\" - a word that names the action, not the thing the person actually came for. When it names the reward instead - \"Get my quote,\" \"See available times,\" \"Send my photos\" - more people tend to finish. It is a two-minute swap, costs nothing, and the logic is simple: label what they get, not what they do. If you try it on your own form, what does the button say right now - and would naming the reward change it?"
  },
  {
    "id": "n08",
    "image": "/posts/kindcodex-n08-stat.png",
    "batch": 1,
    "label": "Texts get read fast",
    "caption": "A small channel detail that explains a lot about why fast-moving teams open with a text instead of an email. Texts tend to get read within a couple of minutes; emails commonly sit unopened for an hour or more (the often-cited figures are roughly 90 seconds vs. 90 minutes). So when someone has just raised their hand and is actively comparing options, the two channels are really reaching them at two different moments - one while they're still leaning in, one after the moment has cooled. A pattern we keep noticing: it's rarely about the channel feeling fancier, just about landing where the person's attention already is. Curious how it works on your end - when a fresh inquiry comes in, what's the default first move: call, text, or email?"
  },
  {
    "id": "n09",
    "image": "/posts/kindcodex-n09-checklist.png",
    "batch": 1,
    "label": "After-hours routing checklist",
    "caption": "Something most teams notice once they look: new leads rarely arrive at a tidy 10 a.m. on a Tuesday. They land after hours, over the weekend, in the middle of a job, or in an inbox no one happens to be watching that minute. Response-time research backs this up — the odds of actually connecting drop sharply the longer the gap, and most of those gaps open at exactly those moments. So here's a small map of the five spots where a lead can slip by, with a sensible, buildable fix beside each — the kind of thing a calendar and a couple of automations can cover, no phone-staring required. Save it as a checklist for your own setup if it's handy. Curious which of the five tends to be the quietest one for you?"
  },
  {
    "id": "n10",
    "image": "/posts/kindcodex-n10-stat.png",
    "batch": 1,
    "label": "Never replied at all",
    "caption": "A number worth sitting with: in a 2024 RevenueHero field test, real demo requests were sent to 1,000 companies, and only about 4 in 10 wrote back. What makes that interesting isn't the silence so much as the math behind who wins the rest. Decades of lead-response research point to the same pattern: buyers tend to reward whoever answers first, and the advantage decays fast - the odds of actually connecting with a fresh inquiry drop sharply within the first hour, and the first credible reply often anchors the whole decision. So in any market where a handful of businesses go quiet, the ones that answer quickly and consistently end up competing against a much smaller field than the headcount suggests. It's less about volume and more about being reliably present at the exact moment someone is curious. Curious what your own corner looks like - when an inquiry lands in your world, how fast does the first real reply usually go out?"
  },
  {
    "id": "n11",
    "image": "/posts/kindcodex-n11-dentist-inmedias.png",
    "batch": 2,
    "label": "Implant dentist",
    "caption": "The patient was already in another dentist's chair when the reply finally went out.\n\nRewind to Tuesday. A full-arch inquiry — the kind of case a practice builds a whole quarter around — landed in the inbox at 10:40am, while the doctor was six hours deep in surgery. Nobody owned the inbox. The reply went out Thursday morning.\n\nHere's the number that reframed it: when Harvard Business Review audited 2,241 companies with a test inquiry, the average response to a web lead took 42 hours — and 23% never answered at all. Composite scene, real pattern.\n\nThe case didn't go to a better surgeon. It went to a faster front desk. Nobody at the practice ever clocked their reply time. Somebody, somewhere, always does. Do you know yours?"
  },
  {
    "id": "n12",
    "image": "/posts/kindcodex-n12-restaurant-taps.png",
    "batch": 2,
    "label": "Restaurant / food truck",
    "caption": "The taqueria thought it had a foot-traffic problem. It had an eleven-tap menu.\n\nThe owner could see people finding the page — the analytics said so. So the obvious answer was \"we need more people\": more posts, maybe ads. Then someone actually counted the taps between \"I'm hungry\" and \"order placed.\" Eleven. Two menus, a PDF that needed pinch-zooming, a third-party ordering portal with its own login.\n\nInterested is fragile. Every extra tap quietly loses the order — the customer doesn't complain, doesn't email, just closes the tab and microwaves something.\n\nOne page, one tap to order, done on a Tuesday. The \"foot-traffic problem\" was never about feet. How many taps between a hungry customer and your kitchen?"
  },
  {
    "id": "n13",
    "image": "/posts/kindcodex-n13-medspa-trustcurve.png",
    "batch": 2,
    "label": "Med spa",
    "caption": "The med spa with a perfect 5.0 keeps losing patients to the one rated 4.6.\n\nThat's not bad luck. Northwestern's Spiegel Research Center analyzed 122,000+ reviews and found purchase likelihood peaks between 4.2 and 4.7 stars — in every category tested. A flawless score trips a quiet alarm in the buyer's head: too good to be true.\n\nWhich means the 3-star review an owner spends weeks trying to get taken down might be doing sales work: it makes the other 40 reviews believable.\n\nThe flaw was the proof all along. What would you stop worrying about if that were true for your business?"
  },
  {
    "id": "n14",
    "image": "/posts/kindcodex-n14-realtor-trust.png",
    "batch": 2,
    "label": "Luxury realtor",
    "caption": "The buyer toured the website for nine minutes. The showing request never came.\n\nNine minutes is a long time on a website — someone was serious. They read the about page, opened three listings, hovered over the contact form. And then something in the picture didn't add up to trust. No recent proof. A form that felt like it went nowhere. Photos that undersold the work.\n\nBuyers size a business up long before they ever call — the decision often happens entirely inside the screen. (Northwestern's review research says the first five reviews alone lift purchase likelihood ~270%, and even more for expensive purchases. The proof does the persuading.)\n\nEveryone optimizes the conversation. Almost nobody optimizes the nine minutes before it. What does your nine-minute tour add up to?"
  },
  {
    "id": "n15",
    "image": "/posts/kindcodex-n15-plaza-whodunit.png",
    "batch": 2,
    "label": "Shopping plaza / commercial landlord",
    "caption": "A fully-leased Honolulu plaza kept losing customers it never knew it had.\n\nRound up the suspects. The prices? Fair — cleared. The tenants? Good operators, loyal regulars — cleared. The parking? Fine once you found it — cleared.\n\nThe culprit: nobody searching could tell what was inside. Twenty businesses, and online the plaza was a gray rectangle with a street address. No directory, no names, no reasons to turn in.\n\nHere's why that's expensive: 76% of people who search \"near me\" visit a business within 24 hours, and 28% of those searches end in a purchase (Google/Ipsos). A \"near me\" search is a person already in motion — they just need something to aim at.\n\nThe plaza never saw the customers it lost, because they never arrived. What does your business look like to someone deciding in the car?"
  },
  {
    "id": "n16",
    "image": "/posts/kindcodex-n16-hvac-twoquotes.png",
    "batch": 2,
    "label": "HVAC / cooling",
    "caption": "Two quotes for the same AC job.\n\nQuote A was thorough. It took four days — measured twice, priced carefully, written up properly.\n\nQuote B was on the customer's screen before the tech left the driveway.\n\nClassic negotiation research (Galinsky & Mussweiler) found that whoever names a number first usually wins — the first offer becomes the anchor every later number gets measured against. By the time the four-day quote arrived, it wasn't being judged on its merits. It was being judged against Quote B.\n\nThe careful company didn't lose on price or on quality. It lost on sequence. If your estimate takes days, whose number is your customer comparing it to?"
  },
  {
    "id": "n17",
    "image": "/posts/kindcodex-n17-wedding-laborillusion.png",
    "batch": 2,
    "label": "Wedding planner / venue",
    "caption": "Her portfolio held forty weddings. Her inquiry page looked like a parking ticket.\n\nForty weddings of vendor wrangling, weather contingencies, seating diplomacy — compressed into \"Name. Email. Submit.\" All that craft, invisible at the exact moment a couple decides who feels worth $30,000.\n\nThere's a studied reason this stings: the Labor Illusion (Buell & Norton, Management Science). People value a service more when they can see the work happening — travel sites that showed \"searching 47 airlines…\" were preferred over instant results. Visible effort reads as value. Hidden effort reads as arbitrary pricing.\n\nShe didn't need a bigger portfolio. She needed the work to be visible before the first phone call. Where does your best work hide?"
  },
  {
    "id": "n18",
    "image": "/posts/kindcodex-n18-surgeon-pen.png",
    "batch": 2,
    "label": "Cosmetic surgeon",
    "caption": "The most valuable instrument at one Honolulu surgery practice is a ballpoint pen.\n\nIt sits at the checkout desk. When a consult gets scheduled, the coordinator slides it across and the patient writes their own appointment card. Staff never fill it in — that's the rule.\n\nUK clinics ran this as a field experiment (Journal of the Royal Society of Medicine, with Cialdini's commitment principle): patients who wrote their own card no-showed 18% less. People don't break commitments they authored.\n\nThe pen costs forty cents. The surgical hour it protects does not. What's the forty-cent fix hiding in your booking flow?"
  },
  {
    "id": "n19",
    "image": "/posts/kindcodex-n19-gym-question.png",
    "batch": 2,
    "label": "Boutique gym",
    "caption": "Out of every 26 members unhappy enough to quit a gym, how many tell the front desk before they go?\n\n26? 13? 5? 1?\n\nDrop your guess in the comments — answer tomorrow. (It's worse than most owners think, and it changes how you read a quiet month.)"
  },
  {
    "id": "n20",
    "image": "/posts/kindcodex-n20-pm-reviews.png",
    "batch": 2,
    "label": "Property management",
    "caption": "The property manager answered every one-star review. Then something strange happened to the rating.\n\nNot the lawsuit-threat kind of answers — calm, specific, named-the-fix answers. It felt like damage control. It turned out to be construction.\n\nMarketing Science research (Proserpio & Zervas) tracked what happens when businesses start responding to reviews: ratings rise (+0.12 stars), review volume grows ~12%, and the angriest one-liners fade — because people write more carefully when they know management actually reads.\n\nFor a PM firm, that public paper trail of handled problems is exactly what a remote owner is looking for: proof that when something breaks at 2am, someone shows up. The reviews section stopped being a wound and became the sales page. What's your reply rate on the reviews you'd rather not have?"
  },
  {
    "id": "n21",
    "image": "/posts/kindcodex-n21-solar-formfriction.png",
    "batch": 2,
    "label": "Solar contractor",
    "caption": "You want solar. You're ready to spend $40,000 today. The form wants your phone number first.\n\nAnd you hesitate — not because you're not serious, but because you know exactly what that field means: three calls tomorrow while you're at work.\n\nForm-analytics research across ~93 million sessions found a required phone field turns away roughly 37% of the people filling out a form. Mark it optional and completions nearly double. The people bouncing aren't tire-kickers; they're buyers who want to choose when the conversation starts.\n\nOne word — \"optional\" — might be the cheapest A/B test in home improvement. What's your form asking for before it's earned it?"
  },
  {
    "id": "n19b",
    "image": "",
    "batch": 2,
    "label": "Gym — reveal (text)",
    "caption": "One. The answer is one.\n\nCustomer-experience researcher Esteban Kolsky found that only 1 in 26 unhappy customers complains. The other 25 don't argue, don't ask for a manager, don't email. They just stop coming — and the front desk reads the silence as satisfaction.\n\nSo a \"quiet quarter\" isn't quiet at all; it's 25 conversations that never happened. The gyms that keep members aren't the ones with suggestion boxes — they're the ones that notice the fade (missed visits, lapsed bookings) before the goodbye that never comes.\n\nTo everyone who guessed 1 yesterday: you've clearly run something. What tipped you off?"
  }
];
